### PR TITLE
Use `/usr/bin/env` for `build.sh`

### LINKED ISSUE #3: build fails when bash is not in `/bin`
Because of the #! : https://github.com/stedolan/ocaml-afl-persistent/blob/723b19cb1dbf2e72a427644433c339757cc90dcc/build.sh#L1

### PR DESCRIPTION
**Pull request by smondet**
Fix #3

### CODE REVIEW

**Comment by hannesm** [comment]
AFAICT (and shellcheck.net agrees with me), `build.sh` is a POSIX sh compatible script -- why use `bash` here, instead of simply `sh`?  is there a good reason for doing so?

**Comment by smondet** [comment]
@hannesm happy to change to `/bin/sh` if there is no plan to use gnu-isms in the future. @stedolan ?

**Comment by stedolan** [comment]
Happy with `/bin/sh`! (It's `/bin/bash` out of habit rather than for any good reason)

**Comment by smondet** [comment]
Tested with `dash` and `busybox` :)

**Comment by stedolan** [comment]
Thanks!

**Pull request merged**
